name: Deploy to server

env:
 DEPLOY_PATH: /tertiusaxis/TertiusAxis/client

on: [push]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v1
        with:
          node-version: '14'
      # Записываем в переменные окружения имя текущей ветки
      # Чтобы избежать конфиликтов с URL, меняем точки на _, а слеши на минусы
      - name: Get branch name
        shell: bash
        run: echo "::set-env name=BRANCH_NAME::$(echo ${GITHUB_REF#refs/heads/} | sed 's/\//-/g' | sed 's/\./_/g')"
      # Устанавливаем зависимости для сборки
      - name: Install Dependencies
        run: npm i
      # Собираем приложение
      - name: Build Appliction
        run: npm run build
    
      - name: Deploy to Server
        uses: garygrossgarten/github-action-scp@release
        with:
          local: testworkflow
          remote: ${{ env.DEPLOY_PATH }}/testWF
          host: ${{ secrets.DEPLOY_SERVER_HOST }}
        
      - name: Print Info
        run: echo "Deployed at ../tertiusaxis/TertiusAxis/client"
