name: CI

env:
 DEPLOY_PATH: /tertiusaxis/TertiusAxis/client

on: [push]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to Server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.DEPLOY_SERVER_HOST }}
          key: ${{ secrets.DEPLOY_SERVER_KEY }}
          source: ico
          target: ${{ env.DEPLOY_PATH }}/testWF
          strip_components: 1
      - name: Print Info
        run: echo "Deployed at ../tertiusaxis/TertiusAxis/client"
